### ISSUE TITLE
Unexpectedly found nil when unwrapping URL for Font

### ISSUE THREAD

**Issue by thomaspaulmann** [Themoji/all#1]
The heading says it all! There is no "Apple Color Emoji" anymore?! 😱

I got the error at the following line: https://github.com/Themoji/all/blob/master/Themoji/FontRendering.swift#L13

Any suggestions to fix that? Does the name change?

**Comment by KrauseFx** [comment]
I think this might have changed with Sierra? Can you run `rake`?

**Comment by thomaspaulmann** [comment]
Thanks for the hint. I totally forgot about that 😬 Anyways, I got an error and you're right. The font changed to '/System/Library/Fonts/Apple Color Emoji.ttc' since Sierra.
